pipeline {
   triggers {
        pollSCM 'H/2 * * * *'
    }
     agent any
    options {
        disableConcurrentBuilds()
    }
    environment {
        APP = "ap-jenkins-basic-nodejs"
    }
    stages {
        stage('Build and Publish APP') {
            steps {
                /*
                * Multiline strings can be used for larger scripts.
                */
                sh """
                git clone https://github.com/aamirpinger/jenkins-basic-nodejs.git
                cd jenkins-basic-nodejs
                docker build -t ${APP} .
                """
            }
        }
        stage('deploy') {
            steps {
                /*
                * Multiline strings can be used for larger scripts. It is also possible to put scripts in your shared library
                * and load them with 'libaryResource'
                */
                sh """
                docker rm ${APP} --force || true
                docker run -d --name ${APP} -p 3000:3000
                """
            }
        }
    }
     post {
        success {
            echo "App can be accessed from http://localhost:3000"
        }
    }
}